In [ ]:
(1, 3, 3, 5)

(16, 3, 3, 5)

In [1]:
import numpy as np
import tensorflow as tf

In [22]:
with tf.Session() as sess:
    batch, height, width, feature = 1, 3, 3, 2

    generated_layer_patches = tf.placeholder(tf.float32, shape=(batch, height, width, feature))
    style_layer_patches_16 = tf.placeholder(tf.float32, shape=(3, height, width, feature))

    init_generated_layer_patches = np.array(
        [[[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]]])
    
    init_style_layer_patches = np.array(
        [
         [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]],
         [[[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
         [[[14, 14], [15, 15], [16, 16]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
        ])
    
    distances = []
    style_layer_patches_per_image = tf.unstack(style_layer_patches_16, axis=0)
    for patches_per_image in style_layer_patches_per_image:
        patches_per_image = tf.expand_dims(patches_per_image, 0)
        distance = tf.losses.cosine_distance(generated_layer_patches, patches_per_image, dim=3)
        distances.append(distance)
    output = tf.stack(distances)
    
    feed_dict = {generated_layer_patches: init_generated_layer_patches, style_layer_patches_16: init_style_layer_patches}
    
    out, patches = sess.run([output, style_layer_patches_per_image], feed_dict=feed_dict)

In [23]:
out

array([-62.33333206, -76.33333588, -89.66666412], dtype=float32)

In [26]:
np.asarray(patches).shape

(3, 3, 3, 2)

In [27]:
np.asarray(patches)[0]

array([[[ 1.,  1.],
        [ 2.,  2.],
        [ 3.,  3.]],

       [[ 4.,  4.],
        [ 5.,  5.],
        [ 6.,  6.]],

       [[ 7.,  7.],
        [ 8.,  8.],
        [ 9.,  9.]]], dtype=float32)

In [28]:
np.asarray(patches)[1]

array([[[ 4.,  4.],
        [ 5.,  5.],
        [ 6.,  6.]],

       [[ 7.,  7.],
        [ 8.,  8.],
        [ 9.,  9.]],

       [[ 7.,  7.],
        [ 8.,  8.],
        [ 9.,  9.]]], dtype=float32)

In [29]:
np.asarray(patches)[2]

array([[[ 14.,  14.],
        [ 15.,  15.],
        [ 16.,  16.]],

       [[  7.,   7.],
        [  8.,   8.],
        [  9.,   9.]],

       [[  7.,   7.],
        [  8.,   8.],
        [  9.,   9.]]], dtype=float32)

In [52]:
with tf.Session() as sess:
    batch, height, width, feature = 1, 3, 3, 2

    generated_layer_patches = tf.placeholder(tf.float32, shape=(batch, height, width, feature))
    style_layer_patches = tf.placeholder(tf.float32, shape=(batch, height, width, feature))

    init_generated_layer_patches = np.array(
        [
            [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]]
        ])
    
    init_style_layer_patches = np.array(
        [
            [[[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
        ])
    
    generated_layer_flat = tf.reshape(generated_layer_patches, [batch, -1, feature])
    style_layer_flat = tf.reshape(generated_layer_patches, [batch, -1, feature])
    
    distance = tf.losses.cosine_distance(generated_layer_patches, style_layer_patches, dim=0)
    
    feed_dict = {generated_layer_patches: init_generated_layer_patches, style_layer_patches: init_style_layer_patches}
    
    out = sess.run([distance], feed_dict=feed_dict)

In [53]:
out

[-37.666668]

In [49]:
np.asarray(_a).shape

(1, 9, 2)

In [50]:
np.asarray(_a)

array([[[ 1.,  1.],
        [ 2.,  2.],
        [ 3.,  3.],
        [ 4.,  4.],
        [ 5.,  5.],
        [ 6.,  6.],
        [ 7.,  7.],
        [ 8.,  8.],
        [ 9.,  9.]]], dtype=float32)

In [133]:
with tf.Session() as sess:
    batch, height, width, feature = 1, 3, 3, 2
    style_batch = 4

    style_layer_patches = tf.placeholder(tf.float32, shape=(style_batch, height, width, feature))
    
    init_style_layer_patches = np.array(
        [
         [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]],
         [[[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
         [[[14, 14], [15, 15], [16, 16]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
         [[[55, 33], [22, 111], [136, 106]], [[17, 17], [85, 85], [95, 95]], [[75, 75], [58, 58], [59, 59]]],   
        ])
    
    style_layer_patches_per_batch = tf.unstack(style_layer_patches)
    test = tf.stack(style_layer_patches_per_batch, axis=2) # (1, 3, 3, style_batch, feature)
    test = tf.reshape(test, [height*width, style_batch, feature])
    
    feed_dict = {style_layer_patches: init_style_layer_patches}
    
    out = sess.run([test], feed_dict=feed_dict)

In [134]:
np.asarray(out).shape

(1, 9, 4, 2)

In [135]:
print(out[0][0].shape)
out[0][0]

(4, 2)


array([[  1.,   1.],
       [  4.,   4.],
       [ 14.,  14.],
       [ 55.,  33.]], dtype=float32)

In [96]:
out[0][1]

array([[[  4.,   4.],
        [  7.,   7.],
        [  7.,   7.],
        [ 17.,  17.]],

       [[  5.,   5.],
        [  8.,   8.],
        [  8.,   8.],
        [ 85.,  85.]],

       [[  6.,   6.],
        [  9.,   9.],
        [  9.,   9.],
        [ 95.,  95.]]], dtype=float32)

In [97]:
out[0][2]

array([[[  7.,   7.],
        [  7.,   7.],
        [  7.,   7.],
        [ 75.,  75.]],

       [[  8.,   8.],
        [  8.,   8.],
        [  8.,   8.],
        [ 58.,  58.]],

       [[  9.,   9.],
        [  9.,   9.],
        [  9.,   9.],
        [ 59.,  59.]]], dtype=float32)

In [ ]:
with tf.Session() as sess:
    batch, height, width, feature = 1, 3, 3, 2

    generated_layer_patches = tf.placeholder(tf.float32, shape=(batch, height, width, feature))
    style_layer_patches = tf.placeholder(tf.float32, shape=(3, height, width, feature))
    
    init_generated_layer_patches = np.array(
        [
            [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]]
        ])
    
    init_style_layer_patches = np.array(
        [
         [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]],
         [[[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
         [[[14, 14], [15, 15], [16, 16]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
        ])
    
    style_layer_patches_per_batch = tf.unstack(style_layer_patches)
    style_layer_join_per_pixel = tf.stack(style_layer_patches_per_batch, axis=2) # (1, 3, 3, style_batch, feature)
    
    feed_dict = {generated_layer_patches: init_generated_layer_patches, style_layer_patches: init_style_layer_patches}
    
    out = sess.run([test], feed_dict=feed_dict)

In [138]:
with tf.Session() as sess:
    batch, height, width, feature = 1, 3, 3, 2

    generated_layer_patches = tf.placeholder(tf.float32, shape=(batch, height, width, feature))
    
    init_generated_layer_patches = np.array(
        [
            [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]]
        ])
    
    feed_dict = {generated_layer_patches: init_generated_layer_patches}
    
    generated_layer_per_pixels = tf.reshape(generated_layer_patches, [-1, feature])
    
    out = sess.run([generated_layer_per_pixels], feed_dict=feed_dict)

In [139]:
np.asarray(out).shape
# (1, 3, 3, 4, 2)

(1, 9, 2)

In [140]:
out

[array([[ 1.,  1.],
        [ 2.,  2.],
        [ 3.,  3.],
        [ 4.,  4.],
        [ 5.,  5.],
        [ 6.,  6.],
        [ 7.,  7.],
        [ 8.,  8.],
        [ 9.,  9.]], dtype=float32)]

In [111]:
out[0][0][0]

array([ 1.,  1.], dtype=float32)

In [109]:
out[0][1]

array([[ 4.,  4.],
       [ 5.,  5.],
       [ 6.,  6.]], dtype=float32)

In [110]:
out[0][2]

array([[ 7.,  7.],
       [ 8.,  8.],
       [ 9.,  9.]], dtype=float32)

In [172]:
with tf.Session() as sess:
    batch, height, width, feature = 1, 3, 3, 2
    style_batch = 4

    style_layer_patches = tf.placeholder(tf.float32, shape=(style_batch, height, width, feature))
    
    init_style_layer_patches = np.array(
        [
         [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]],
         [[[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
         [[[14, 14], [15, 15], [16, 16]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
         [[[55, 33], [22, 111], [136, 106]], [[17, 17], [85, 85], [95, 95]], [[75, 75], [58, 58], [59, 59]]],   
        ])
    
    generated_layer_patches = tf.placeholder(tf.float32, shape=(batch, height, width, feature))
    
    init_generated_layer_patches = np.array(
        [
            [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]]
        ])
    
    style_layer_patches_per_batch = tf.unstack(style_layer_patches)
    style_layer_join_by_per_batch = tf.stack(style_layer_patches_per_batch, axis=2) # (1, 3, 3, style_batch, feature)
    style_layer_join_by_per_feature = tf.reshape(style_layer_join_by_per_batch, [height*width, style_batch, feature]) # (1, 9, style_batch, feature)
    size, _, _ = style_layer_join_by_per_feature.get_shape().as_list()
    
#     for i in tf.range(size):
#         print(i)
    c = tf.unstack()
    
    
    generated_layer_per_pixels = tf.reshape(generated_layer_patches, [-1, feature])
    
    feed_dict = {generated_layer_patches: init_generated_layer_patches, style_layer_patches: init_style_layer_patches}
    
    style, generated = sess.run([style_layer_join_by_per_feature, generated_layer_per_pixels], feed_dict=feed_dict)

In [175]:
size

9

In [176]:
np.asarray(style)

array([[[   1.,    1.],
        [   4.,    4.],
        [  14.,   14.],
        [  55.,   33.]],

       [[   2.,    2.],
        [   5.,    5.],
        [  15.,   15.],
        [  22.,  111.]],

       [[   3.,    3.],
        [   6.,    6.],
        [  16.,   16.],
        [ 136.,  106.]],

       [[   4.,    4.],
        [   7.,    7.],
        [   7.,    7.],
        [  17.,   17.]],

       [[   5.,    5.],
        [   8.,    8.],
        [   8.,    8.],
        [  85.,   85.]],

       [[   6.,    6.],
        [   9.,    9.],
        [   9.,    9.],
        [  95.,   95.]],

       [[   7.,    7.],
        [   7.,    7.],
        [   7.,    7.],
        [  75.,   75.]],

       [[   8.,    8.],
        [   8.,    8.],
        [   8.,    8.],
        [  58.,   58.]],

       [[   9.,    9.],
        [   9.,    9.],
        [   9.,    9.],
        [  59.,   59.]]], dtype=float32)

In [159]:
np.asarray(generated).shape

(9, 2)

In [160]:
np.asarray(style)

array([[[   1.,    1.],
        [   4.,    4.],
        [  14.,   14.],
        [  55.,   33.]],

       [[   2.,    2.],
        [   5.,    5.],
        [  15.,   15.],
        [  22.,  111.]],

       [[   3.,    3.],
        [   6.,    6.],
        [  16.,   16.],
        [ 136.,  106.]],

       [[   4.,    4.],
        [   7.,    7.],
        [   7.,    7.],
        [  17.,   17.]],

       [[   5.,    5.],
        [   8.,    8.],
        [   8.,    8.],
        [  85.,   85.]],

       [[   6.,    6.],
        [   9.,    9.],
        [   9.,    9.],
        [  95.,   95.]],

       [[   7.,    7.],
        [   7.,    7.],
        [   7.,    7.],
        [  75.,   75.]],

       [[   8.,    8.],
        [   8.,    8.],
        [   8.,    8.],
        [  58.,   58.]],

       [[   9.,    9.],
        [   9.,    9.],
        [   9.,    9.],
        [  59.,   59.]]], dtype=float32)

In [6]:
# argmin test
with tf.Session() as sess:
    style_pixel = tf.placeholder(tf.float32, shape=(4, 2))
    generate_pixel = tf.placeholder(tf.float32, shape=(2))
    
    init_style_pixel = np.array(
        [[   1.,    1.], [   4.,    4.], [  14.,   14.], [  55.,   33.]])
    
    init_generate_pixel = np.array([ 1., 2. ])

    feed_dict = {style_pixel: init_style_pixel, generate_pixel: init_generate_pixel}
    
    ret = []
    for pixel in tf.unstack(style_pixel):
        ret.append(tf.losses.cosine_distance(pixel, generate_pixel, dim=0))
    ret = tf.stack(ret)
    min_result = tf.reduce_min(ret)
    argmin = tf.argmin(ret)
    best_match = tf.gather(style_pixel, indices=argmin)
    out, _min = sess.run([best_match, min_result], feed_dict=feed_dict)

In [7]:
_min

-120.0

In [203]:
out

array([ 55.,  33.], dtype=float32)

In [186]:
out

array([  -2.,  -11.,  -41., -120.], dtype=float32)

In [205]:
with tf.Session() as sess:
    print(sess.run(tf.losses.cosine_distance([   55.,    33.], [   1.,    2.] , dim=0)))

-120.0


In [259]:
with tf.Session() as sess:
    batch, height, width, feature = 1, 3, 3, 2
    style_batch = 4

    style_layer_patches = tf.placeholder(tf.float32, shape=(style_batch, height, width, feature))
    
    init_style_layer_patches = np.array(
        [
         [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]],
         [[[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
         [[[14, 14], [15, 15], [16, 16]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
         [[[55, 33], [22, 111], [136, 106]], [[17, 17], [85, 85], [95, 95]], [[75, 75], [58, 58], [59, 59]]],   
        ])
    
    generated_layer_patches = tf.placeholder(tf.float32, shape=(batch, height, width, feature))
    
    init_generated_layer_patches = np.array(
        [
            [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]]
        ])
    
    concat_generate_style_layer = tf.concat([generated_layer_patches, style_layer_patches], 0)
#     style_layer_patches_per_batch = tf.unstack(style_layer_patches)
    style_layer_patches_per_batch = tf.unstack(concat_generate_style_layer)
    style_layer_join_by_per_batch = tf.stack(style_layer_patches_per_batch, axis=2) # (1, 3, 3, style_batch, feature)
    style_layer_join_by_per_feature = tf.reshape(style_layer_join_by_per_batch, [height*width, (style_batch + batch), feature]) # (9, style_batch, feature)
    
#     generated_layer_per_pixels = tf.reshape(generated_layer_patches, [-1, feature]) # (9, 2)
    
    for layer in tf.unstack(style_layer_join_by_per_feature):
        g_patch, s_patches = tf.split(layer, [batch, style_batch], 0)
        g_patch = tf.squeeze(g_patch)
        ret = []
        for pixel in tf.unstack(s_patches):
            ret.append(tf.losses.cosine_distance(pixel, g_patch, dim=0))
        ret = tf.stack(ret)
        argmin = tf.argmin(ret)
        best_match = tf.gather(style_pixel, indices=argmin)
    
    feed_dict = {generated_layer_patches: init_generated_layer_patches, style_layer_patches: init_style_layer_patches}
    
    out = sess.run([style_layer_join_by_per_feature], feed_dict=feed_dict)

In [260]:
concat_generate_style_layer

<tf.Tensor 'concat_22:0' shape=(5, 3, 3, 2) dtype=float32>

In [257]:
out

[array([[[   1.,    1.],
         [   1.,    1.],
         [   4.,    4.],
         [  14.,   14.],
         [  55.,   33.]],
 
        [[   2.,    2.],
         [   2.,    2.],
         [   5.,    5.],
         [  15.,   15.],
         [  22.,  111.]],
 
        [[   3.,    3.],
         [   3.,    3.],
         [   6.,    6.],
         [  16.,   16.],
         [ 136.,  106.]],
 
        [[   4.,    4.],
         [   4.,    4.],
         [   7.,    7.],
         [   7.,    7.],
         [  17.,   17.]],
 
        [[   5.,    5.],
         [   5.,    5.],
         [   8.,    8.],
         [   8.,    8.],
         [  85.,   85.]],
 
        [[   6.,    6.],
         [   6.,    6.],
         [   9.,    9.],
         [   9.,    9.],
         [  95.,   95.]],
 
        [[   7.,    7.],
         [   7.,    7.],
         [   7.,    7.],
         [   7.,    7.],
         [  75.,   75.]],
 
        [[   8.,    8.],
         [   8.,    8.],
         [   8.,    8.],
         [   8.,    8.],
    

In [253]:
layer

<tf.Tensor 'unstack_75:0' shape=(5, 2) dtype=float32>

In [248]:
g_patch

<tf.Tensor 'split_9:0' shape=(1, 2) dtype=float32>

In [251]:
s_patches

<tf.Tensor 'split_18:1' shape=(?, 2) dtype=float32>

In [245]:
np.asarray(out).shape

(1, 9, 5, 2)

In [246]:
out

[array([[[   1.,    1.],
         [   1.,    1.],
         [   4.,    4.],
         [  14.,   14.],
         [  55.,   33.]],
 
        [[   2.,    2.],
         [   2.,    2.],
         [   5.,    5.],
         [  15.,   15.],
         [  22.,  111.]],
 
        [[   3.,    3.],
         [   3.,    3.],
         [   6.,    6.],
         [  16.,   16.],
         [ 136.,  106.]],
 
        [[   4.,    4.],
         [   4.,    4.],
         [   7.,    7.],
         [   7.,    7.],
         [  17.,   17.]],
 
        [[   5.,    5.],
         [   5.,    5.],
         [   8.,    8.],
         [   8.,    8.],
         [  85.,   85.]],
 
        [[   6.,    6.],
         [   6.,    6.],
         [   9.,    9.],
         [   9.,    9.],
         [  95.,   95.]],
 
        [[   7.,    7.],
         [   7.,    7.],
         [   7.,    7.],
         [   7.,    7.],
         [  75.,   75.]],
 
        [[   8.,    8.],
         [   8.,    8.],
         [   8.,    8.],
         [   8.,    8.],
    

In [207]:
np.asarray(style).shape

(9, 4, 2)

In [208]:
np.asarray(generated).shape

(9, 2)

In [215]:
# concat test
with tf.Session() as sess:
    t1 = np.asarray([[1, 2, 3], [4, 5, 6]])
#     t2 = np.asarray([[7, 8, 9], [10, 11, 12]])
    split0, split1 = tf.split(t1, [1, 1], 0)

In [216]:
split0

<tf.Tensor 'split:0' shape=(1, 3) dtype=int64>

In [15]:
with tf.Session() as sess:
    batch, height, width, feature = 1, 3, 3, 2
    style_batch = 4

    style_layer_patches = tf.placeholder(tf.float32, shape=(style_batch, height, width, feature))
    
    init_style_layer_patches = np.array(
        [
         [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]],
         [[[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
         [[[14, 14], [15, 15], [16, 16]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
         [[[55, 33], [22, 111], [136, 106]], [[17, 17], [85, 85], [95, 95]], [[75, 75], [58, 58], [59, 59]]],   
        ])
    
    generated_layer_patches = tf.placeholder(tf.float32, shape=(batch, height, width, feature))
    
    init_generated_layer_patches = np.array(
        [
            [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]]
        ])
    
    concat_generate_style_layer = tf.concat([generated_layer_patches, style_layer_patches], 0)
    style_layer_patches_per_batch = tf.unstack(concat_generate_style_layer)
    style_layer_join_by_per_batch = tf.stack(style_layer_patches_per_batch, axis=2) # (1, 3, 3, style_batch, feature)
    style_layer_join_by_per_feature = tf.reshape(style_layer_join_by_per_batch, [height*width, (style_batch + batch), feature]) # (9, style_batch, feature)
    
#     generated_layer_per_pixels = tf.reshape(generated_layer_patches, [-1, feature]) # (9, 2)
    
    ## for batch in baches::
    style_loss = []
    for layer in tf.unstack(style_layer_join_by_per_feature):
        g_patch, s_patches = tf.split(layer, [1, style_batch], 0)
        g_patch = tf.squeeze(g_patch)
        ret = []
        for pixel in tf.unstack(s_patches):
            ret.append(tf.losses.cosine_distance(pixel, g_patch, dim=0))
        ret = tf.stack(ret)
        min_patch = tf.reduce_min(ret)
        style_loss.append(min_patch)
#         argmin = tf.argmin(ret)
#         best_match = tf.gather(s_patches, indices=argmin)
    style_loss = tf.reduce_mean(tf.stack(style_loss))
    
    feed_dict = {generated_layer_patches: init_generated_layer_patches, style_layer_patches: init_style_layer_patches}
    
    out = sess.run([style_loss], feed_dict=feed_dict)

In [16]:
out

[-693.0]

In [14]:
with tf.Session() as sess:
    print(sess.run(tf.losses.cosine_distance([   8.,    8.], [   8.,    8.] , dim=0)))

-127.0


In [3]:
# answer
with tf.Session() as sess:
    batch, height, width, feature = 2, 3, 3, 2
    style_batch = 4

    style_layer_patches = tf.placeholder(tf.float32, shape=(style_batch, height, width, feature))
    
    init_style_layer_patches = np.array(
        [
         [[[3, 3], [71, 71], [37, 37]], [[47, 47], [57, 57], [67, 67]], [[77, 77], [87, 87], [97, 97]]],
         [[[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
         [[[14, 14], [15, 15], [16, 16]], [[7, 7], [8, 8], [9, 9]], [[27, 27], [28, 28], [29, 29]]],
         [[[55, 33], [22, 111], [136, 106]], [[17, 17], [85, 85], [95, 95]], [[75, 75], [58, 58], [59, 59]]],   
        ])
    
    generated_layer_patches = tf.placeholder(tf.float32, shape=(batch, height, width, feature))
    
    init_generated_layer_patches = np.array(
        [
            [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]],
            [[[41, 41], [42, 42], [43, 43]], [[44, 44], [45, 45], [46, 46]], [[47, 47], [48, 48], [49, 49]]]
        ])
    
#     concat_generate_style_layer = tf.concat([generated_layer_patches, style_layer_patches], 0)
    
    concat_layer = []
    for g_layer_per_batch in tf.unstack(generated_layer_patches):
        g_layer_per_batch = tf.expand_dims(g_layer_per_batch, 0)
        concat_generate_style_layer = tf.concat([g_layer_per_batch, style_layer_patches], 0)
        concat_layer.append(concat_generate_style_layer)
    concat_layer = tf.squeeze(tf.stack(concat_layer))
    
    style_layer_patches_per_batch = tf.unstack(concat_layer, axis=1)
    style_layer_join_by_per_batch = tf.stack(style_layer_patches_per_batch, axis=3)
    style_layer_join_by_per_feature = tf.reshape(style_layer_join_by_per_batch, [batch, height*width, (style_batch + 1), feature]) 
    
    total_style_loss = 0
    for batch_layer in tf.unstack(style_layer_join_by_per_feature):
        style_loss_per_batch = []
        for layer in tf.unstack(batch_layer):
            g_patch, s_patches = tf.split(layer, [1, style_batch], 0)
            g_patch = tf.squeeze(g_patch)
            ret = []
            for pixel in tf.unstack(s_patches):
                ret.append(tf.losses.cosine_distance(pixel, g_patch, dim=0))
            ret = tf.stack(ret)
            min_patch = tf.reduce_min(ret)
            style_loss_per_batch.append(min_patch)
    #         argmin = tf.argmin(ret)
    #         best_match = tf.gather(s_patches, indices=argmin)
        style_loss_per_batch = tf.reduce_mean(tf.stack(style_loss_per_batch))
        total_style_loss += style_loss_per_batch
    
    total_style_loss = total_style_loss/batch
    feed_dict = {generated_layer_patches: init_generated_layer_patches, style_layer_patches: init_style_layer_patches}
    
    out = sess.run([total_style_loss], feed_dict=feed_dict)
    
    

In [85]:
out

[-4070.1111]

In [78]:
np.asarray(out).shape

(1, 2, 9, 5, 2)

In [81]:
np.asarray(out)[0][1]

array([[[  41.,   41.],
        [   3.,    3.],
        [   4.,    4.],
        [  14.,   14.],
        [  55.,   33.]],

       [[  42.,   42.],
        [  71.,   71.],
        [   5.,    5.],
        [  15.,   15.],
        [  22.,  111.]],

       [[  43.,   43.],
        [  37.,   37.],
        [   6.,    6.],
        [  16.,   16.],
        [ 136.,  106.]],

       [[  44.,   44.],
        [  47.,   47.],
        [   7.,    7.],
        [   7.,    7.],
        [  17.,   17.]],

       [[  45.,   45.],
        [  57.,   57.],
        [   8.,    8.],
        [   8.,    8.],
        [  85.,   85.]],

       [[  46.,   46.],
        [  67.,   67.],
        [   9.,    9.],
        [   9.,    9.],
        [  95.,   95.]],

       [[  47.,   47.],
        [  77.,   77.],
        [   7.,    7.],
        [  27.,   27.],
        [  75.,   75.]],

       [[  48.,   48.],
        [  87.,   87.],
        [   8.,    8.],
        [  28.,   28.],
        [  58.,   58.]],

       [[  49.,   49.],


In [60]:
np.asarray(out)[0][1]

array([[[[  41.,   41.],
         [  42.,   42.],
         [  43.,   43.]],

        [[  44.,   44.],
         [  45.,   45.],
         [  46.,   46.]],

        [[  47.,   47.],
         [  48.,   48.],
         [  49.,   49.]]],


       [[[   3.,    3.],
         [  71.,   71.],
         [  37.,   37.]],

        [[  47.,   47.],
         [  57.,   57.],
         [  67.,   67.]],

        [[  77.,   77.],
         [  87.,   87.],
         [  97.,   97.]]],


       [[[   4.,    4.],
         [   5.,    5.],
         [   6.,    6.]],

        [[   7.,    7.],
         [   8.,    8.],
         [   9.,    9.]],

        [[   7.,    7.],
         [   8.,    8.],
         [   9.,    9.]]],


       [[[  14.,   14.],
         [  15.,   15.],
         [  16.,   16.]],

        [[   7.,    7.],
         [   8.,    8.],
         [   9.,    9.]],

        [[  27.,   27.],
         [  28.,   28.],
         [  29.,   29.]]],


       [[[  55.,   33.],
         [  22.,  111.],
         [ 136.,  

In [13]:
np.asarray(out)[0][1]

array([[[[  41.,   41.],
         [  42.,   42.],
         [  43.,   43.]],

        [[  44.,   44.],
         [  45.,   45.],
         [  46.,   46.]],

        [[  47.,   47.],
         [  48.,   48.],
         [  49.,   49.]]],


       [[[   1.,    1.],
         [   2.,    2.],
         [   3.,    3.]],

        [[   4.,    4.],
         [   5.,    5.],
         [   6.,    6.]],

        [[   7.,    7.],
         [   8.,    8.],
         [   9.,    9.]]],


       [[[   4.,    4.],
         [   5.,    5.],
         [   6.,    6.]],

        [[   7.,    7.],
         [   8.,    8.],
         [   9.,    9.]],

        [[   7.,    7.],
         [   8.,    8.],
         [   9.,    9.]]],


       [[[  14.,   14.],
         [  15.,   15.],
         [  16.,   16.]],

        [[   7.,    7.],
         [   8.,    8.],
         [   9.,    9.]],

        [[   7.,    7.],
         [   8.,    8.],
         [   9.,    9.]]],


       [[[  55.,   33.],
         [  22.,  111.],
         [ 136.,  