In [1]:
import numpy as np
import tensorflow as tf

In [48]:
sess = tf.InteractiveSession()


# vgg_generated_images (batch, hegith, width, feature)
# => (batch, style_n_best, height, width, feature)

# idx = tf.range(style_n_best)


yp = [1,2,3]
idx = tf.range(len(yp))
print(idx.eval())
idx = tf.reshape(idx, [-1, 1])# Convert to a len(yp) x 1 matrix.
print(idx.eval())
print(idx.shape)
idx = tf.tile(idx, [1, len(yp)])  # Create multiple columns.
print(idx.eval())
idx = tf.reshape(idx, [-1])       # Convert back to a vector.
print(idx.eval())
sess.close()

[0 1 2]
[[0]
 [1]
 [2]]
(3, 1)
[[0 0 0]
 [1 1 1]
 [2 2 2]]
[0 0 0 1 1 1 2 2 2]


In [7]:
# tf.tile test
with tf.Session() as sess:
    batch, height, width, feature = 2, 3, 3, 2
    style_n_best = 3

    vgg_generated_images = tf.placeholder(tf.float32, shape=(batch, height, width, feature))
    
    init_vgg_generated_images = np.array(
        [
            [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]],
            [[[11, 11], [12, 12], [13, 13]], [[14, 14], [15, 15], [16, 16]], [[17, 17], [18, 18], [19, 19]]]
        ])
    
    test = tf.tile(vgg_generated_images, [1, style_n_best, 1, 1])
    
    feed_dict = {vgg_generated_images: init_vgg_generated_images}
    
    out = sess.run(test, feed_dict=feed_dict)    

In [8]:
out.shape

(2, 9, 3, 2)

In [9]:
out

array([[[[  1.,   1.],
         [  2.,   2.],
         [  3.,   3.]],

        [[  4.,   4.],
         [  5.,   5.],
         [  6.,   6.]],

        [[  7.,   7.],
         [  8.,   8.],
         [  9.,   9.]],

        [[  1.,   1.],
         [  2.,   2.],
         [  3.,   3.]],

        [[  4.,   4.],
         [  5.,   5.],
         [  6.,   6.]],

        [[  7.,   7.],
         [  8.,   8.],
         [  9.,   9.]],

        [[  1.,   1.],
         [  2.,   2.],
         [  3.,   3.]],

        [[  4.,   4.],
         [  5.,   5.],
         [  6.,   6.]],

        [[  7.,   7.],
         [  8.,   8.],
         [  9.,   9.]]],


       [[[ 11.,  11.],
         [ 12.,  12.],
         [ 13.,  13.]],

        [[ 14.,  14.],
         [ 15.,  15.],
         [ 16.,  16.]],

        [[ 17.,  17.],
         [ 18.,  18.],
         [ 19.,  19.]],

        [[ 11.,  11.],
         [ 12.,  12.],
         [ 13.,  13.]],

        [[ 14.,  14.],
         [ 15.,  15.],
         [ 16.,  16.]],

    

In [22]:
with tf.Session() as sess:
    batch, height, width, feature = 2, 3, 3, 2
    style_n_best = 3
    
    vgg_style_best = tf.placeholder(tf.float32, shape=(batch, style_n_best, height, width, feature))
    
    init_vgg_style_best = np.array(
        [
            [
             [[[101, 101], [102, 102], [103, 103]], [[104, 104], [105, 105], [106, 106]], [[107, 107], [108, 108], [109, 109]]],
             [[[111, 111], [112, 112], [113, 113]], [[114, 114], [115, 115], [116, 116]], [[117, 117], [118, 118], [119, 119]]],
             [[[151, 151], [152, 152], [153, 153]], [[154, 154], [155, 155], [156, 156]], [[157, 157], [158, 158], [159, 159]]]
            ],
            [
             [[[201, 201], [202, 202], [203, 203]], [[204, 204], [205, 205], [206, 206]], [[207, 207], [208, 208], [209, 209]]],
             [[[301, 301], [302, 302], [303, 303]], [[304, 304], [305, 305], [306, 306]], [[307, 307], [308, 308], [309, 309]]],
             [[[401, 401], [402, 402], [403, 403]], [[404, 404], [405, 405], [406, 406]], [[407, 407], [408, 408], [409, 409]]]
            ]
        ]
    )
    
    vgg_generated_images = tf.placeholder(tf.float32, shape=(batch, height, width, feature))
    
    init_vgg_generated_images = np.array(
        [
            [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]],
            [[[11, 11], [12, 12], [13, 13]], [[14, 14], [15, 15], [16, 16]], [[17, 17], [18, 18], [19, 19]]]
        ])

    concat = tf.concat([vgg_generated_images, vgg_generated_images], 1)
    concat = tf.concat([concat, vgg_generated_images], 1)
    
    concat = tf.reshape(concat, [batch, style_n_best, height, width, feature])
    
    feed_dict = {vgg_style_best: init_vgg_style_best, vgg_generated_images: init_vgg_generated_images}
    
    out = sess.run(concat, feed_dict=feed_dict)

In [24]:
out

array([[[[[  1.,   1.],
          [  2.,   2.],
          [  3.,   3.]],

         [[  4.,   4.],
          [  5.,   5.],
          [  6.,   6.]],

         [[  7.,   7.],
          [  8.,   8.],
          [  9.,   9.]]],


        [[[  1.,   1.],
          [  2.,   2.],
          [  3.,   3.]],

         [[  4.,   4.],
          [  5.,   5.],
          [  6.,   6.]],

         [[  7.,   7.],
          [  8.,   8.],
          [  9.,   9.]]],


        [[[  1.,   1.],
          [  2.,   2.],
          [  3.,   3.]],

         [[  4.,   4.],
          [  5.,   5.],
          [  6.,   6.]],

         [[  7.,   7.],
          [  8.,   8.],
          [  9.,   9.]]]],



       [[[[ 11.,  11.],
          [ 12.,  12.],
          [ 13.,  13.]],

         [[ 14.,  14.],
          [ 15.,  15.],
          [ 16.,  16.]],

         [[ 17.,  17.],
          [ 18.,  18.],
          [ 19.,  19.]]],


        [[[ 11.,  11.],
          [ 12.,  12.],
          [ 13.,  13.]],

         [[ 14.,  14.],
    

In [22]:
concat

<tf.Tensor 'concat_4:0' shape=(2, 6, 3, 2) dtype=float32>

In [24]:
concat

<tf.Tensor 'concat_6:0' shape=(2, 9, 3, 2) dtype=float32>

In [29]:
i = tf.constant(0)
while_condition = lambda i: tf.less(i, style_n_best)
def body(i):
    concat = tf.concat([vgg_generated_images, vgg_generated_images], 1)
    # do something here which you want to do in your loop
    # increment i
    return [tf.add(i, 1)]

# do the loop:
r = tf.while_loop(while_condition, body, [i])

In [25]:
def body(x):
    return tf.concat([x, vgg_generated_images], 1)

def condition(x):
    batch, key, _, _  = x.get_shape().as_list()
    return key < (style_n_best * height)

In [ ]:
def body(x):
    a = tf.random_uniform(shape=[2, 2], dtype=tf.int32, maxval=100)
    b = tf.constant(np.array([[1, 2], [3, 4]]), dtype=tf.int32)
    c = a + b
    return tf.nn.relu(x + c)

def condition(x):
    return tf.reduce_sum(x) < 100

x = tf.Variable(tf.constant(0, shape=[2, 2]))

with tf.Session():
    tf.initialize_all_variables().run()
    result = tf.while_loop(condition, body, [x])
    print(result.eval())

In [20]:
out[0]

array([[[[ 1.,  1.],
         [ 2.,  2.],
         [ 3.,  3.]],

        [[ 4.,  4.],
         [ 5.,  5.],
         [ 6.,  6.]],

        [[ 7.,  7.],
         [ 8.,  8.],
         [ 9.,  9.]]],


       [[[ 1.,  1.],
         [ 2.,  2.],
         [ 3.,  3.]],

        [[ 4.,  4.],
         [ 5.,  5.],
         [ 6.,  6.]],

        [[ 7.,  7.],
         [ 8.,  8.],
         [ 9.,  9.]]],


       [[[ 1.,  1.],
         [ 2.,  2.],
         [ 3.,  3.]],

        [[ 4.,  4.],
         [ 5.,  5.],
         [ 6.,  6.]],

        [[ 7.,  7.],
         [ 8.,  8.],
         [ 9.,  9.]]]], dtype=float32)

In [6]:
init_vgg_style_best.shape

(2, 3, 3, 3, 2)

In [7]:
init_vgg_generated_images.shape

(2, 3, 3, 2)

In [ ]:
# answer
with tf.Session() as sess:
    batch, height, width, feature = 2, 3, 3, 2
    style_batch = 4

    style_layer_patches = tf.placeholder(tf.float32, shape=(style_batch, height, width, feature))
    
    init_style_layer_patches = np.array(
        [
         [[[3, 3], [71, 71], [37, 37]], [[47, 47], [57, 57], [67, 67]], [[77, 77], [87, 87], [97, 97]]],
         [[[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]], [[7, 7], [8, 8], [9, 9]]],
         [[[14, 14], [15, 15], [16, 16]], [[7, 7], [8, 8], [9, 9]], [[27, 27], [28, 28], [29, 29]]],
         [[[55, 33], [22, 111], [136, 106]], [[17, 17], [85, 85], [95, 95]], [[75, 75], [58, 58], [59, 59]]],   
        ])
    
    generated_layer_patches = tf.placeholder(tf.float32, shape=(batch, height, width, feature))
    
    init_generated_layer_patches = np.array(
        [
            [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]],
            [[[41, 41], [42, 42], [43, 43]], [[44, 44], [45, 45], [46, 46]], [[47, 47], [48, 48], [49, 49]]]
        ])
    
#     concat_generate_style_layer = tf.concat([generated_layer_patches, style_layer_patches], 0)
    
    concat_layer = []
    for g_layer_per_batch in tf.unstack(generated_layer_patches):
        g_layer_per_batch = tf.expand_dims(g_layer_per_batch, 0)
        concat_generate_style_layer = tf.concat([g_layer_per_batch, style_layer_patches], 0)
        concat_layer.append(concat_generate_style_layer)
    concat_layer = tf.squeeze(tf.stack(concat_layer))
    
    style_layer_patches_per_batch = tf.unstack(concat_layer, axis=1)
    style_layer_join_by_per_batch = tf.stack(style_layer_patches_per_batch, axis=3)
    style_layer_join_by_per_feature = tf.reshape(style_layer_join_by_per_batch, [batch, height*width, (style_batch + 1), feature]) 
    
    total_style_loss = 0
    for batch_layer in tf.unstack(style_layer_join_by_per_feature):
        style_loss_per_batch = []
        for layer in tf.unstack(batch_layer):
            g_patch, s_patches = tf.split(layer, [1, style_batch], 0)
            g_patch = tf.squeeze(g_patch)
            ret = []
            for pixel in tf.unstack(s_patches):
                ret.append(tf.losses.cosine_distance(pixel, g_patch, dim=0))
            ret = tf.stack(ret)
            min_patch = tf.reduce_min(ret)
            style_loss_per_batch.append(min_patch)
    #         argmin = tf.argmin(ret)
    #         best_match = tf.gather(s_patches, indices=argmin)
        style_loss_per_batch = tf.reduce_mean(tf.stack(style_loss_per_batch))
        total_style_loss += style_loss_per_batch
    
    total_style_loss = total_style_loss/batch
    feed_dict = {generated_layer_patches: init_generated_layer_patches, style_layer_patches: init_style_layer_patches}
    
    out = sess.run([total_style_loss], feed_dict=feed_dict)

In [107]:
with tf.Session() as sess:
    batch, height, width, feature = 2, 3, 3, 2
    style_n_best = 3
    
    vgg_style_best = tf.placeholder(tf.float32, shape=(batch, style_n_best, height, width, feature))
    
    init_vgg_style_best = np.array(
        [
            [
             [[[101, 101], [102, 102], [103, 103]], [[104, 104], [105, 105], [106, 106]], [[107, 107], [108, 108], [109, 109]]],
             [[[111, 111], [112, 112], [113, 113]], [[114, 114], [115, 115], [116, 116]], [[117, 117], [118, 118], [119, 119]]],
             [[[151, 151], [152, 152], [153, 153]], [[154, 154], [155, 155], [156, 156]], [[157, 157], [158, 158], [159, 159]]]
            ],
            [
             [[[201, 201], [202, 202], [203, 203]], [[204, 204], [205, 205], [206, 206]], [[207, 207], [208, 208], [209, 209]]],
             [[[301, 301], [302, 302], [303, 303]], [[304, 304], [305, 305], [306, 306]], [[307, 307], [308, 308], [309, 309]]],
             [[[401, 401], [402, 402], [403, 403]], [[404, 404], [405, 405], [406, 406]], [[407, 407], [408, 408], [409, 409]]]
            ]
        ]
    )
    
    vgg_generated_images = tf.placeholder(tf.float32, shape=(batch, height, width, feature))
    
    init_vgg_generated_images = np.array(
        [
            [[[1, 1], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]],
            [[[11, 11], [12, 12], [13, 13]], [[14, 14], [15, 15], [16, 16]], [[17, 17], [18, 18], [19, 19]]]
        ])

    vgg_generatd_images_repeat_by_style_n_best = tf.tile(vgg_generated_images, [1, style_n_best, 1, 1])
    vgg_generatd_images_repeat_by_style_n_best = tf.reshape(vgg_generatd_images_repeat_by_style_n_best, [batch, style_n_best, height, width, feature])
#     params = tf.stack([vgg_generatd_images_repeat_by_style_n_best, vgg_style_best], 1)
    
    
#     distances = tf.map_fn(lambda x: tf.losses.cosine_distance(x[0][2], x[1][2], dim=0), (vgg_generatd_images_repeat_by_style_n_best, vgg_style_best), tf.float32)
#     distances = tf.losses.cosine_distance(vgg_generatd_images_repeat_by_style_n_best, vgg_style_best, dim=1)

#     normalize_g = tf.nn.l2_normalize(vgg_generatd_images_repeat_by_style_n_best, 4)        
#     normalize_s = tf.nn.l2_normalize(vgg_style_best, 4)
    cos_distance = tf.squeeze((1 - tf.reduce_sum(tf.multiply(vgg_generatd_images_repeat_by_style_n_best, vgg_style_best), 4)))
    cos_distance_min = tf.reduce_min(cos_distance, 1)
    style_loss = tf.reduce_mean(cos_distance_min)
    
    feed_dict = {vgg_style_best: init_vgg_style_best, vgg_generated_images: init_vgg_generated_images}
    
    out, out_c = sess.run([style_loss, cos_distance_min], feed_dict=feed_dict)

In [111]:
out

-6862.3335

In [84]:
with tf.Session() as sess:
    print(sess.run(tf.losses.cosine_distance([   409.,    409.], [   19.,    19.] , dim=0)))

-15541.0


In [90]:
np.asarray(out).shape

(1, 2, 3, 3)

In [112]:
np.mean(out_c)

-6862.3335

In [80]:
out

[array([[[[  -201.,   -407.,   -617.],
          [  -831.,  -1049.,  -1271.],
          [ -1497.,  -1727.,  -1961.]],
 
         [[  -221.,   -447.,   -677.],
          [  -911.,  -1149.,  -1391.],
          [ -1637.,  -1887.,  -2141.]],
 
         [[  -301.,   -607.,   -917.],
          [ -1231.,  -1549.,  -1871.],
          [ -2197.,  -2527.,  -2861.]]],
 
 
        [[[ -4421.,  -4847.,  -5277.],
          [ -5711.,  -6149.,  -6591.],
          [ -7037.,  -7487.,  -7941.]],
 
         [[ -6621.,  -7247.,  -7877.],
          [ -8511.,  -9149.,  -9791.],
          [-10437., -11087., -11741.]],
 
         [[ -8821.,  -9647., -10477.],
          [-11311., -12149., -12991.],
          [-13837., -14687., -15541.]]]], dtype=float32)]

In [40]:
out

array([[[[[  1.,   1.],
          [  2.,   2.],
          [  3.,   3.]],

         [[  4.,   4.],
          [  5.,   5.],
          [  6.,   6.]],

         [[  7.,   7.],
          [  8.,   8.],
          [  9.,   9.]]],


        [[[  1.,   1.],
          [  2.,   2.],
          [  3.,   3.]],

         [[  4.,   4.],
          [  5.,   5.],
          [  6.,   6.]],

         [[  7.,   7.],
          [  8.,   8.],
          [  9.,   9.]]],


        [[[  1.,   1.],
          [  2.,   2.],
          [  3.,   3.]],

         [[  4.,   4.],
          [  5.,   5.],
          [  6.,   6.]],

         [[  7.,   7.],
          [  8.,   8.],
          [  9.,   9.]]]],



       [[[[ 11.,  11.],
          [ 12.,  12.],
          [ 13.,  13.]],

         [[ 14.,  14.],
          [ 15.,  15.],
          [ 16.,  16.]],

         [[ 17.,  17.],
          [ 18.,  18.],
          [ 19.,  19.]]],


        [[[ 11.,  11.],
          [ 12.,  12.],
          [ 13.,  13.]],

         [[ 14.,  14.],
    

In [12]:
vgg_generatd_images_repeat_by_style_n_best

<tf.Tensor 'Reshape_4:0' shape=(2, 3, 3, 3, 2) dtype=float32>

In [13]:
vgg_style_best

<tf.Tensor 'Placeholder_8:0' shape=(2, 3, 3, 3, 2) dtype=float32>

In [161]:
### answer
with tf.Session() as sess:
    batch, height, width, feature = 2, 3, 3, 2
    style_n_best = 3
    
    vgg_style_best = tf.placeholder(tf.float32, shape=(batch, style_n_best, height, width, feature))
    
    init_vgg_style_best = np.array(
        [
            [
             [[[255, 125], [102, 102], [103, 103]], [[104, 104], [105, 105], [106, 106]], [[107, 107], [108, 108], [109, 109]]],
             [[[111, 111], [112, 112], [113, 113]], [[114, 114], [115, 115], [116, 116]], [[117, 117], [118, 118], [119, 119]]],
             [[[151, 151], [152, 152], [153, 153]], [[154, 154], [155, 155], [156, 156]], [[157, 157], [158, 158], [159, 159]]]
            ],
            [
             [[[201, 201], [202, 202], [203, 203]], [[204, 204], [205, 205], [206, 206]], [[207, 207], [208, 208], [209, 209]]],
             [[[301, 301], [302, 302], [303, 303]], [[304, 304], [305, 305], [306, 306]], [[307, 307], [308, 308], [309, 309]]],
             [[[401, 401], [402, 402], [403, 403]], [[404, 404], [405, 405], [406, 406]], [[407, 407], [408, 408], [409, 409]]]
            ]
        ]
    )
    
    vgg_generated_images = tf.placeholder(tf.float32, shape=(batch, height, width, feature))
    
    init_vgg_generated_images = np.array(
        [
            [[[5, 113], [2, 2], [3, 3]], [[4, 4], [5, 5], [6, 6]], [[7, 7], [8, 8], [9, 9]]],
            [[[11, 11], [12, 12], [13, 13]], [[14, 14], [15, 15], [16, 16]], [[17, 17], [18, 18], [19, 19]]]
        ])

    vgg_generatd_images_repeat_by_style_n_best = tf.tile(vgg_generated_images, [1, style_n_best, 1, 1])
    vgg_generatd_images_repeat_by_style_n_best = tf.reshape(vgg_generatd_images_repeat_by_style_n_best, [batch, style_n_best, height, width, feature])

    normalize_g = tf.nn.l2_normalize(vgg_generatd_images_repeat_by_style_n_best, 4)
    normalize_s = tf.nn.l2_normalize(vgg_style_best, 4)

    cos_distance = tf.squeeze((1 - tf.reduce_sum(tf.multiply(normalize_g, normalize_s), 4)))
    cos_distance_min = tf.reduce_min(cos_distance, 1)
    style_loss = tf.reduce_mean(cos_distance_min)
    
    feed_dict = {vgg_style_best: init_vgg_style_best, vgg_generated_images: init_vgg_generated_images}
    
    out, out_c = sess.run([style_loss, cos_distance], feed_dict=feed_dict)
#     out, out_c_m, out_c, n_g, n_s, g, s  = sess.run([style_loss, cos_distance_min, cos_distance, normalize_g, normalize_s, vgg_generatd_images_repeat_by_style_n_best, vgg_style_best], feed_dict=feed_dict)

In [163]:
out

0.014573806

In [160]:
with tf.Session() as sess:
    normalize_g = tf.nn.l2_normalize([  255.,   125.], dim=0)
    normalize_s = tf.nn.l2_normalize([   5.,    113.], dim=0)
    print(sess.run(tf.losses.cosine_distance(normalize_g, normalize_s, dim=0)))

0.520581


In [162]:
out_c

array([[[[  5.20580828e-01,   5.96046448e-08,   1.78813934e-07],
         [  1.78813934e-07,   1.19209290e-07,   1.19209290e-07],
         [  5.96046448e-08,   1.19209290e-07,   1.78813934e-07]],

        [[  2.62327075e-01,   1.78813934e-07,   5.96046448e-08],
         [  5.96046448e-08,   1.19209290e-07,   1.19209290e-07],
         [  1.19209290e-07,   1.19209290e-07,   1.19209290e-07]],

        [[  2.62327075e-01,   1.19209290e-07,   1.19209290e-07],
         [  1.19209290e-07,   1.19209290e-07,   1.78813934e-07],
         [  1.19209290e-07,   1.78813934e-07,   1.19209290e-07]]],


       [[[  5.96046448e-08,   1.78813934e-07,   1.19209290e-07],
         [  5.96046448e-08,   1.19209290e-07,   1.78813934e-07],
         [  1.19209290e-07,   1.78813934e-07,   5.96046448e-08]],

        [[  0.00000000e+00,   1.19209290e-07,   1.19209290e-07],
         [  1.19209290e-07,   1.78813934e-07,   1.19209290e-07],
         [  5.96046448e-08,   1.19209290e-07,   1.19209290e-07]],

        [[  5

In [147]:
g

array([[[[[  1.,  10.],
          [  2.,   2.],
          [  3.,   3.]],

         [[  4.,   4.],
          [  5.,   5.],
          [  6.,   6.]],

         [[  7.,   7.],
          [  8.,   8.],
          [  9.,   9.]]],


        [[[  1.,  10.],
          [  2.,   2.],
          [  3.,   3.]],

         [[  4.,   4.],
          [  5.,   5.],
          [  6.,   6.]],

         [[  7.,   7.],
          [  8.,   8.],
          [  9.,   9.]]],


        [[[  1.,  10.],
          [  2.,   2.],
          [  3.,   3.]],

         [[  4.,   4.],
          [  5.,   5.],
          [  6.,   6.]],

         [[  7.,   7.],
          [  8.,   8.],
          [  9.,   9.]]]],



       [[[[ 11.,  11.],
          [ 12.,  12.],
          [ 13.,  13.]],

         [[ 14.,  14.],
          [ 15.,  15.],
          [ 16.,  16.]],

         [[ 17.,  17.],
          [ 18.,  18.],
          [ 19.,  19.]]],


        [[[ 11.,  11.],
          [ 12.,  12.],
          [ 13.,  13.]],

         [[ 14.,  14.],
    

In [148]:
s

array([[[[[ 101.,  110.],
          [ 102.,  102.],
          [ 103.,  103.]],

         [[ 104.,  104.],
          [ 105.,  105.],
          [ 106.,  106.]],

         [[ 107.,  107.],
          [ 108.,  108.],
          [ 109.,  109.]]],


        [[[ 111.,  111.],
          [ 112.,  112.],
          [ 113.,  113.]],

         [[ 114.,  114.],
          [ 115.,  115.],
          [ 116.,  116.]],

         [[ 117.,  117.],
          [ 118.,  118.],
          [ 119.,  119.]]],


        [[[ 151.,  151.],
          [ 152.,  152.],
          [ 153.,  153.]],

         [[ 154.,  154.],
          [ 155.,  155.],
          [ 156.,  156.]],

         [[ 157.,  157.],
          [ 158.,  158.],
          [ 159.,  159.]]]],



       [[[[ 201.,  201.],
          [ 202.,  202.],
          [ 203.,  203.]],

         [[ 204.,  204.],
          [ 205.,  205.],
          [ 206.,  206.]],

         [[ 207.,  207.],
          [ 208.,  208.],
          [ 209.,  209.]]],


        [[[ 301.,  301.],
    

In [149]:
n_g

array([[[[[ 0.09950372,  0.9950372 ],
          [ 0.70710671,  0.70710671],
          [ 0.70710671,  0.70710671]],

         [[ 0.70710671,  0.70710671],
          [ 0.70710671,  0.70710671],
          [ 0.70710671,  0.70710671]],

         [[ 0.70710671,  0.70710671],
          [ 0.70710671,  0.70710671],
          [ 0.70710671,  0.70710671]]],


        [[[ 0.09950372,  0.9950372 ],
          [ 0.70710671,  0.70710671],
          [ 0.70710671,  0.70710671]],

         [[ 0.70710671,  0.70710671],
          [ 0.70710671,  0.70710671],
          [ 0.70710671,  0.70710671]],

         [[ 0.70710671,  0.70710671],
          [ 0.70710671,  0.70710671],
          [ 0.70710671,  0.70710671]]],


        [[[ 0.09950372,  0.9950372 ],
          [ 0.70710671,  0.70710671],
          [ 0.70710671,  0.70710671]],

         [[ 0.70710671,  0.70710671],
          [ 0.70710671,  0.70710671],
          [ 0.70710671,  0.70710671]],

         [[ 0.70710671,  0.70710671],
          [ 0.70710671,  0.707

In [150]:
n_s

array([[[[[ 0.6763308 ,  0.73659796],
          [ 0.70710683,  0.70710683],
          [ 0.70710671,  0.70710671]],

         [[ 0.70710671,  0.70710671],
          [ 0.70710677,  0.70710677],
          [ 0.70710677,  0.70710677]],

         [[ 0.70710683,  0.70710683],
          [ 0.70710677,  0.70710677],
          [ 0.70710671,  0.70710671]]],


        [[[ 0.70710677,  0.70710677],
          [ 0.70710671,  0.70710671],
          [ 0.70710683,  0.70710683]],

         [[ 0.70710683,  0.70710683],
          [ 0.70710677,  0.70710677],
          [ 0.70710677,  0.70710677]],

         [[ 0.70710677,  0.70710677],
          [ 0.70710677,  0.70710677],
          [ 0.70710677,  0.70710677]]],


        [[[ 0.70710677,  0.70710677],
          [ 0.70710677,  0.70710677],
          [ 0.70710677,  0.70710677]],

         [[ 0.70710677,  0.70710677],
          [ 0.70710677,  0.70710677],
          [ 0.70710671,  0.70710671]],

         [[ 0.70710677,  0.70710677],
          [ 0.70710671,  0.707

In [132]:
np.asarray(out_c).shape

(2, 3, 3, 3)

In [152]:
out_c

array([[[[  1.99760199e-01,   5.96046448e-08,   1.78813934e-07],
         [  1.78813934e-07,   1.19209290e-07,   1.19209290e-07],
         [  5.96046448e-08,   1.19209290e-07,   1.78813934e-07]],

        [[  2.26042688e-01,   1.78813934e-07,   5.96046448e-08],
         [  5.96046448e-08,   1.19209290e-07,   1.19209290e-07],
         [  1.19209290e-07,   1.19209290e-07,   1.19209290e-07]],

        [[  2.26042688e-01,   1.19209290e-07,   1.19209290e-07],
         [  1.19209290e-07,   1.19209290e-07,   1.78813934e-07],
         [  1.19209290e-07,   1.78813934e-07,   1.19209290e-07]]],


       [[[  5.96046448e-08,   1.78813934e-07,   1.19209290e-07],
         [  5.96046448e-08,   1.19209290e-07,   1.78813934e-07],
         [  1.19209290e-07,   1.78813934e-07,   5.96046448e-08]],

        [[  0.00000000e+00,   1.19209290e-07,   1.19209290e-07],
         [  1.19209290e-07,   1.78813934e-07,   1.19209290e-07],
         [  5.96046448e-08,   1.19209290e-07,   1.19209290e-07]],

        [[  5

In [151]:
with tf.Session() as sess:
    normalize_g = tf.nn.l2_normalize([  1.,   10.], dim=0)
    normalize_s = tf.nn.l2_normalize([   101.,    110.], dim=0)
    print(sess.run(normalize_g)) #0.70710671
    print(sess.run(normalize_s))
    print(sess.run(tf.losses.cosine_distance(normalize_g, normalize_s, dim=0)))

[ 0.09950373  0.99503726]
[ 0.67633086  0.73659796]
0.19976


In [128]:
normalize_g

<tf.Tensor 'l2_normalize_21:0' shape=(2,) dtype=float32>