In [1]:
import numpy as np
import tensorflow as tf

In [9]:
# parmeters
batch, height, width, channel = 5, 3, 3, 2
test_landmarks = 2*2
test_style_images_num = 5
test_style_n_best = 3

In [31]:
with tf.Session() as sess:    
    style_images = tf.placeholder(tf.float32, shape=(batch, height, width, channel))
    
    init_style_images = np.array(
        [
            [[[201, 201], [202, 202], [203, 203]], [[204, 204], [205, 205], [206, 206]], [[207, 207], [208, 208], [209, 209]]],
            [[[301, 301], [302, 302], [303, 303]], [[304, 304], [305, 305], [306, 306]], [[307, 307], [308, 308], [309, 309]]],
            [[[401, 401], [402, 402], [403, 403]], [[404, 404], [405, 405], [406, 406]], [[407, 407], [408, 408], [409, 409]]],
            [[[501, 501], [502, 502], [503, 503]], [[504, 504], [505, 505], [506, 506]], [[507, 507], [508, 508], [509, 509]]],
            [[[601, 601], [602, 602], [603, 603]], [[604, 604], [605, 605], [606, 606]], [[607, 607], [608, 608], [609, 609]]]
        ])
    
    test = tf.reduce_sum(style_images)
    test_0 = tf.reduce_sum(style_images, axis=0)
    test_1 = tf.reduce_sum(style_images, axis=1)
    test_2 = tf.reduce_sum(style_images, axis=2)
    test_3 = tf.reduce_sum(style_images, axis=3)
            
    feed_dict = {
        style_images: init_style_images,
    }

    out, out0, out1, out2, out3 = sess.run([test, test_0, test_1, test_2, test_3], feed_dict=feed_dict)

In [32]:
out

36450.0

In [33]:
out0

array([[[ 2005.,  2005.],
        [ 2010.,  2010.],
        [ 2015.,  2015.]],

       [[ 2020.,  2020.],
        [ 2025.,  2025.],
        [ 2030.,  2030.]],

       [[ 2035.,  2035.],
        [ 2040.,  2040.],
        [ 2045.,  2045.]]], dtype=float32)

In [34]:
out1

array([[[  612.,   612.],
        [  615.,   615.],
        [  618.,   618.]],

       [[  912.,   912.],
        [  915.,   915.],
        [  918.,   918.]],

       [[ 1212.,  1212.],
        [ 1215.,  1215.],
        [ 1218.,  1218.]],

       [[ 1512.,  1512.],
        [ 1515.,  1515.],
        [ 1518.,  1518.]],

       [[ 1812.,  1812.],
        [ 1815.,  1815.],
        [ 1818.,  1818.]]], dtype=float32)

In [35]:
out2

array([[[  606.,   606.],
        [  615.,   615.],
        [  624.,   624.]],

       [[  906.,   906.],
        [  915.,   915.],
        [  924.,   924.]],

       [[ 1206.,  1206.],
        [ 1215.,  1215.],
        [ 1224.,  1224.]],

       [[ 1506.,  1506.],
        [ 1515.,  1515.],
        [ 1524.,  1524.]],

       [[ 1806.,  1806.],
        [ 1815.,  1815.],
        [ 1824.,  1824.]]], dtype=float32)

In [36]:
out3

array([[[  402.,   404.,   406.],
        [  408.,   410.,   412.],
        [  414.,   416.,   418.]],

       [[  602.,   604.,   606.],
        [  608.,   610.,   612.],
        [  614.,   616.,   618.]],

       [[  802.,   804.,   806.],
        [  808.,   810.,   812.],
        [  814.,   816.,   818.]],

       [[ 1002.,  1004.,  1006.],
        [ 1008.,  1010.,  1012.],
        [ 1014.,  1016.,  1018.]],

       [[ 1202.,  1204.,  1206.],
        [ 1208.,  1210.,  1212.],
        [ 1214.,  1216.,  1218.]]], dtype=float32)